apiVersion: apps/v1
kind: Deployment
metadata:
  name: henrik-notes
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: henrik-notes
          image: "ghcr.io/hknots/henrik-notes:sha-7eafe5b"
          imagePullPolicy: IfNotPresent
          env:
            - name: logging.level.no.fintlabs.kurstest
              value: DEBUG
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
              cpu: 25m
            requests:
              memory: 64Mi
              cpu: 25m